version: '3'
services:
  wika:
    build: .
    image: x20ab/wikanode:latest
    volumes:
      - /var/db_wika:/var/db_wika
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    command: --name "node_name" --bob --unsafe-ws-external --rpc-cors=all  --rpc-external --ws-external  --pruning archive
             #--port 30333 
             #--ws-port 9944 
             #--rpc-port 9933 
